import { Link } from "react-router-dom";
import { GlassCard } from "../components/GlassCard";

const lastUpdated = "June 12, 2026";

const sections = [
  {
    title: "1. Information We Collect",
    body: "We may collect information you provide directly, information generated by your use of the platform, and technical information needed to operate and secure the service.",
  },
  {
    title: "2. Account and Profile Data",
    body: "Account data may include your name, email address, role, password credentials, profile details, settings, and communication preferences. Passwords should be stored in protected form and should not be visible to platform staff.",
  },
  {
    title: "3. Learning and Progress Data",
    body: "We may process course enrollments, lesson activity, quiz attempts, scores, notes, saved courses, watch progress, and dashboard metrics so the platform can provide learning features and progress tracking.",
  },
  {
    title: "4. Payments and Providers",
    body: "Payments and subscriptions may be processed by third-party payment providers. IntellectX should not store full card numbers unless a future implementation explicitly adds that capability with appropriate safeguards. Provider transaction identifiers and subscription status may be stored for account and support purposes.",
  },
  {
    title: "5. Cookies and Local Storage",
    body: "The app may use cookies, local storage, or session storage for authentication state, preferences, UI state, and product functionality. For example, theme preference and session-related data may be stored locally in the browser.",
  },
  {
    title: "6. Analytics",
    body: "Analytics tooling is not described here as final. If analytics is enabled, this policy should be updated to identify what is collected, why it is used, and any providers involved.",
  },
  {
    title: "7. AI Feature Data",
    body: "AI-assisted features may process prompts, generated responses, saved takeaways, or related learning context if enabled. If these features are used in production, the handling of AI inputs and outputs should be reviewed and documented clearly.",
  },
  {
    title: "8. Data Sharing",
    body: "We may share data with service providers that help operate the platform, such as hosting, storage, email, payment, security, and support providers. We may also share information if required by law, to protect rights and safety, or with your direction.",
  },
  {
    title: "9. Data Retention",
    body: "We keep information for as long as needed to provide the service, comply with legal obligations, resolve disputes, maintain security, and support legitimate business operations. Retention periods may vary by data type.",
  },
  {
    title: "10. User Choices and Account Deletion",
    body: "Users may be able to update certain profile or account information in the app. Account deletion and data export workflows should be confirmed before launch; until then, users can contact support to request help with account or data questions.",
  },
  {
    title: "11. Children and Minors",
    body: "IntellectX is not intended for children under the age required by applicable law to use online services without consent. If the platform is offered to minors through schools or institutions, additional consent and privacy requirements may apply.",
  },
  {
    title: "12. Security",
    body: "We use reasonable administrative, technical, and organizational measures designed to protect information. No online service can guarantee absolute security, and users should keep their credentials private.",
  },
  {
    title: "13. Changes to This Policy",
    body: "We may update this policy as the product, data practices, providers, or legal requirements change. Material updates should be communicated through the product or another appropriate channel.",
  },
  {
    title: "14. Contact",
    body: "Contact placeholder pending legal review: support@intellectx.app.",
  },
];

export function PrivacyPage() {
  return (
    <div className="mx-auto max-w-4xl px-4 pb-20">
      <GlassCard className="space-y-8">
        <header className="space-y-3 border-b border-gray-200 pb-6">
          <p className="text-xs font-semibold uppercase tracking-widest text-[#4a9ff5]">
            Draft for legal review
          </p>
          <h1 className="text-4xl font-semibold text-gray-900">Privacy Policy</h1>
          <p className="text-sm text-gray-600">Last updated: {lastUpdated}</p>
          <p className="text-gray-700">
            This draft privacy policy describes expected platform data practices and should be reviewed by qualified legal counsel before launch.
          </p>
        </header>

        <div className="space-y-6">
          {sections.map((section) => (
            <section key={section.title} className="rounded-lg border border-gray-100 bg-white/60 p-5">
              <h2 className="mb-2 text-lg font-semibold text-gray-900">{section.title}</h2>
              <p className="leading-7 text-gray-700">{section.body}</p>
            </section>
          ))}
        </div>

        <footer className="border-t border-gray-200 pt-6 text-sm text-gray-600">
          See also the{" "}
          <Link to="/terms" className="font-semibold text-[#4a9ff5] hover:text-[#2e8ef7]">
            Terms of Service
          </Link>
          .
        </footer>
      </GlassCard>
    </div>
  );
}
